development:
  sessions:
    default:
      database: auth_example
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      databse: auth_example_test
      hosts:
        - localhost:27017